### PR TITLE
feat: add build specific runtime functions

### PR DESCRIPTION
**Pull request by cognifloyd**
In kubernetes native secrets and a variety of `VELA_` variables do not get populated in the pod environment.

This was happening because container environment is immutable after pod creation. So, we need to run `Runtime.SetupContainer` for all containers before we create the pod in kubernetes. Then, we have to move `container.Env` initialization to just before pod creation, so that all of the vars that get populated *AFTER* `SetupContainer` make it to the container.

So, I added 4 methods to the `Runtime` engine interface in go-vela/pkg-executor#179 :
- `SetupBuild`
- `AssembleBuild`
- `RemoveBuild`
- `InspectBuild`

This allows us to manage the pod at the build level instead of using heuristics to try and manage creating/removing the pod in the container management functions.

### CODE REVIEW

**Comment by cognifloyd** [comment]
OK. That was more involved than I thought.
It turns out, beyond creating the Pod at the wrong time, we were also setting the `container.Env` too early. The docker runtime defers creating the environment until `Runtime.RunContainer` is called. The kubernetes runtime moved this to `Runtime.SetupContainer`, but much of the environment does not get initialized/set until *AFTER* `SetupContainer` in `Executor.CreateStep` and `Executor.PlanStep`. So, I moved the `container.Env` creation from `Runtime.SetupContainer` to `Runtime.AssembleBuild` + `Runtime.setupContainerEnvironment`.

Now, finally, variables are getting populated as I expect with my custom build of the worker (which includes this PR and go-vela/pkg-executor#179). For example, these variables were not making it to the container, but now they are:
- `VELA_DISTRIBUTION`, `VELA_BUILD_DISTRIBUTION`
- `VELA_RUNTIME`, `VELA_BUILD_RUNTIME`, `BUILD_RUNTIME`, `VELA_STEP_RUNTIME`
- `VELA_VERSION`
- `VELA_BUILD_ENQUEUED`, `BUILD_ENQUEUED`
- `VELA_BUILD_HOST`, `BUILD_HOST`, `VELA_STEP_HOST`
- `VELA_BUILD_STARTED`, `BUILD_STARTED`
- `VELA_BUILD_STATUS`, `BUILD_STATUS`
- native secrets

There are 2 variables that are unknown until each step starts, which is after the build has started and the pod has been created. So, if they are needed, we'll need some other solution for retrieving them (possibly via an vela-server API call in the script). These two vars will always have these values in kubernetes runtime for now:
- `VELA_STEP_STARTED=0`
- `VELA_STEP_STATUS=pending`

**Review by jbrockopp — DISMISSED** [review]
LGTM

**Comment by cognifloyd** [comment]
I just added a docstring.

**Review by KellyMerrick — APPROVED** [review]
lgtm

**Review by jbrockopp — APPROVED** [review]
LGTM

**Pull request merged**
